import { getDb, type PQCommandDb } from "@/db/client";
import {
  acquisitionExclusions,
  acquisitionMissions,
  acquisitionMissionRuns,
  agentMessages,
  analyticsFunnelSnapshots,
  aiConclusions,
  companies,
  contacts,
  conversations,
  deals,
  demandHeatmapCells,
  directnessAssessments,
  documents,
  evidence,
  economicsSignals,
  jobRuns,
  lhaRates,
  leadScoringConfigs,
  leads,
  matches,
  messages,
  notifications,
  objectives,
  outreachDrafts,
  outreachCampaigns,
  outreachMessages,
  pqQuestObjectives,
  pqQuestProfiles,
  pqQuestXpEvents,
  pilotFeedback,
  propertyMedia,
  queueItems,
  replyIntelligenceEvents,
  relationshipGraphEdges,
  requirements,
  signals,
  shortageIntelligenceRows,
  sources,
  suppressionList,
  tasks,
  followUpQueue,
  outreachSendAttempts,
  users,
  viewings,
  workerControls,
  workerHealthSnapshots,
} from "@/db/schema";

import { createAuditRepository } from "./audit-repository";
import { createRepository } from "./base-repository";
import { createPropertyRepository } from "./property-repository";
import { createDemandRoomRepository } from "./demand-room-repository";
import { createMatchingRepository } from "./matching-repository";
import { createShortageIntelligenceRepository } from "./shortage-intelligence-repository";
import { createEconomicsSignalRepository } from "./economics-signal-repository";
import { createViewingWorkflowRepository } from "./viewing-workflow-repository";
import { createDealRoomRepository } from "./deal-room-repository";

export function createRepositories(db: PQCommandDb = getDb()) {
  return {
    users: createRepository(db, users, "usr"),
    companies: createRepository(db, companies, "co"),
    contacts: createRepository(db, contacts, "ctc"),
    properties: createPropertyRepository(db),
    propertyMedia: createRepository(db, propertyMedia, "med"),
    documents: createRepository(db, documents, "doc"),
    requirements: createRepository(db, requirements, "req"),
    leads: createRepository(db, leads, "led"),
    signals: createRepository(db, signals, "sig"),
    evidence: createRepository(db, evidence, "evd"),
    aiConclusions: createRepository(db, aiConclusions, "aic"),
    leadScoringConfigs: createRepository(db, leadScoringConfigs, "lsc"),
    sources: createRepository(db, sources, "src"),
    outreachCampaigns: createRepository(db, outreachCampaigns, "cam"),
    outreachDrafts: createRepository(db, outreachDrafts, "drf"),
    outreachMessages: createRepository(db, outreachMessages, "omg"),
    conversations: createRepository(db, conversations, "cnv"),
    messages: createRepository(db, messages, "msg"),
    replyIntelligenceEvents: createRepository(db, replyIntelligenceEvents, "rie"),
    outreachSendAttempts: createRepository(db, outreachSendAttempts, "sat"),
    followUpQueue: createRepository(db, followUpQueue, "fuq"),
    shortageIntelligenceRows: createRepository(db, shortageIntelligenceRows, "shr"),
    lhaRates: createRepository(db, lhaRates, "lha"),
    economicsSignals: createRepository(db, economicsSignals, "eco"),
    matches: createRepository(db, matches, "mat"),
    viewings: createRepository(db, viewings, "viw"),
    deals: createRepository(db, deals, "del"),
    tasks: createRepository(db, tasks, "tsk"),
    notifications: createRepository(db, notifications, "ntf"),
    objectives: createRepository(db, objectives, "obj"),
    auditEvents: createAuditRepository(db),
    suppressionList: createRepository(db, suppressionList, "sup"),
    jobRuns: createRepository(db, jobRuns, "job"),
    workerControls: createRepository(db, workerControls, "wct"),
    queueItems: createRepository(db, queueItems, "que"),
    workerHealthSnapshots: createRepository(db, workerHealthSnapshots, "whs"),
    pqQuestProfiles: createRepository(db, pqQuestProfiles, "pqp"),
    pqQuestXpEvents: createRepository(db, pqQuestXpEvents, "pqe"),
    pqQuestObjectives: createRepository(db, pqQuestObjectives, "pqo"),
    analyticsFunnelSnapshots: createRepository(db, analyticsFunnelSnapshots, "afs"),
    directnessAssessments: createRepository(db, directnessAssessments, "das"),
    acquisitionMissions: createRepository(db, acquisitionMissions, "mis"),
    acquisitionMissionRuns: createRepository(db, acquisitionMissionRuns, "msr"),
    demandHeatmapCells: createRepository(db, demandHeatmapCells, "dhm"),
    acquisitionExclusions: createRepository(db, acquisitionExclusions, "aex"),
    relationshipGraphEdges: createRepository(db, relationshipGraphEdges, "rge"),
    agentMessages: createRepository(db, agentMessages, "agm"),
    pilotFeedback: createRepository(db, pilotFeedback, "plf"),
    demandRoom: createDemandRoomRepository(db),
    matching: createMatchingRepository(db),
    shortageIntelligence: createShortageIntelligenceRepository(db),
    economicsSignalsRepo: createEconomicsSignalRepository(db),
    viewingWorkflow: createViewingWorkflowRepository(db),
    dealRoom: createDealRoomRepository(db),
  };
}

export type RepositoryCatalog = ReturnType<typeof createRepositories>;
